trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  NODE_VERSION: '18.x'
  IMAGE_NAME: 'prueba-devops'
  REGISTRY: 'docker.io'
  DOCKER_REPO: 'aucancelaa/prueba-devops'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: "Instalar Node.js"

  - script: npm install
    displayName: "Instalar dependencias"

  - script: npm test -- --coverage
    displayName: "Ejecutar tests con Jest"

  - task: Docker@2
    displayName: "Build & Push Docker image"
    inputs:
      command: buildAndPush
      repository: $(DOCKER_REPO)
      dockerfile: '**/Dockerfile'
      containerRegistry: 'DockerHub-Service-Connection'
      tags: |
        latest
        $(Build.BuildId)

  - script: |
      echo "Escaneo de vulnerabilidades con Trivy"
      trivy image $(DOCKER_REPO):latest
    displayName: "Trivy Scan"
